'use client';
import { useState, useRef, useCallback } from "react";
import { Lora } from "next/font/google";

const lora = Lora({ subsets: ["latin"], weight: ["400", "500", "600", "700"], style: ["normal", "italic"] });

const KEYS = ["Keep original","C","C#/Db","D","D#/Eb","E","F","F#/Gb","G","G#/Ab","A","A#/Bb","B"];
const DIFFS = [
  {id:"beginner",label:"Beginner",emoji:"🌱",desc:"Simple triads, single melody"},
  {id:"intermediate",label:"Intermediate",emoji:"🌿",desc:"7th chords, basic voicings"},
  {id:"advanced",label:"Advanced",emoji:"🌸",desc:"Extensions, full arrangements"},
  {id:"expert",label:"Expert",emoji:"🌟",desc:"Concert-level, full harmony"},
];

const GEMINI_KEY = process.env.NEXT_PUBLIC_GEMINI_KEY || "";

const STEPS = ["Upload", "Choose Key", "Choose Level", "Preview"];

export default function Home() {
  const [step, setStep] = useState(0);
  const [image, setImage] = useState<string|null>(null);
  const [imageBase64, setImageBase64] = useState<{data:string,type:string}|null>(null);
  const [targetKey, setTargetKey] = useState("Keep original");
  const [difficulty, setDifficulty] = useState("");
  const [result, setResult] = useState<string|null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string|null>(null);
  const [dragOver, setDragOver] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  const handleFile = useCallback((file: File) => {
    if (!file || !file.type.startsWith("image/")) return;
    setResult(null); setError(null);
    setImage(URL.createObjectURL(file));
    const reader = new FileReader();
    reader.onload = (e) => {
      const b64 = (e.target?.result as string).split(",")[1];
      setImageBase64({ data: b64, type: file.type });
    };
    reader.readAsDataURL(file);
    setStep(1);
  }, []);

  const handleConvert = async () => {
    if (!imageBase64) return;
    setLoading(true); setError(null); setResult(null);
    const diff = DIFFS.find(d => d.id === difficulty);
    const keyInstruction = targetKey === "Keep original"
      ? "Keep the original key as written in the score."
      : `Transpose everything to the key of ${targetKey}.`;
    const prompt = `You are a warm, encouraging piano coach. Analyze this sheet music carefully.
1. Identify: title, original key, time signature, tempo, chords, melody, lyrics
2. ${keyInstruction}
3. Arrange for ${diff?.label} piano level (${diff?.desc})

Format your response beautifully:

🎵 SONG INFO
Title, key, time signature, tempo

🎹 LEAD SHEET
For each section (Intro, Verse, Chorus, Bridge): label, chords, melody, lyrics

✋ PIANO ARRANGEMENT NOTES
Voicings, left hand patterns, fingering tips for ${diff?.label} level

💡 PRACTICE TIPS
3 encouraging, specific tips for this piece and level`;
    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_KEY}`,
        { method:"POST", headers:{"Content-Type":"application/json"},
          body: JSON.stringify({ contents:[{ parts:[
            { inline_data:{ mime_type: imageBase64.type, data: imageBase64.data }},
            { text: prompt }
          ]}]})
        }
      );
      const data = await res.json();
      if (data.error) throw new Error(data.error.message);
      setResult(data.candidates?.[0]?.content?.parts?.[0]?.text || "");
      setStep(3);
    } catch(err: any) {
      setError(err.message);
    } finally { setLoading(false); }
  };

  const handleDownloadPDF = () => {
    if (!result) return;
    const diff = DIFFS.find(d => d.id === difficulty);
    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Irene's Piano Coach — Lead Sheet</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;1,400&display=swap');
  body { font-family: 'Lora', Georgia, serif; max-width: 680px; margin: 40px auto; padding: 0 32px; color: #1a1a2e; line-height: 1.8; }
  h1 { color: #4a90d9; font-size: 28px; margin-bottom: 4px; }
  .meta { color: #7a8fa6; font-style: italic; font-size: 14px; margin-bottom: 32px; }
  pre { white-space: pre-wrap; font-family: 'Lora', Georgia, serif; font-size: 14px; line-height: 1.9; }
  .footer { margin-top: 48px; text-align: center; color: #b0c4d8; font-style: italic; font-size: 12px; }
</style>
</head>
<body>
<h1>🎹 Irene's Piano Coach</h1>
<div class="meta">Key: ${targetKey} &nbsp;·&nbsp; Level: ${diff?.label}</div>
<pre>${result}</pre>
<div class="footer">Generated by Irene's Piano Coach · powered by Gemini</div>
</body>
</html>`;
    const blob = new Blob([html], {type:"text/html"});
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `piano-coach-${targetKey}-${difficulty}.html`;
    a.click();
  };

  const canProceedToKey = !!image;
  const canProceedToLevel = !!targetKey;
  const canPreview = !!difficulty;

  const selectedDiff = DIFFS.find(d => d.id === difficulty);

  return (
    <main className={lora.className} style={{
      minHeight:"100vh",
      background:"linear-gradient(135deg, #e8f4fd 0%, #fef9e7 50%, #e8f8f0 100%)",
      padding:"0 0 80px",
    }}>

      {/* Hero header */}
      <div style={{
        background:"linear-gradient(135deg, #4a90d9 0%, #7bc8a4 100%)",
        padding:"40px 24px 60px",
        textAlign:"center",
        position:"relative",
        overflow:"hidden",
      }}>
        {/* Decorative notes */}
        {["𝄞","𝄢","♩","♪","♫","♬"].map((n,i) => (
          <span key={i} style={{
            position:"absolute",
            fontSize:i%2===0 ? 28 : 20,
            color:"rgba(255,255,255,0.18)",
            top: [10,20,8,18,5,15][i]+"%",
            left: [5,15,75,85,45,92][i]+"%",
            transform:`rotate(${[-15,10,-8,12,-5,8][i]}deg)`,
            userSelect:"none",
          }}>{n}</span>
        ))}
        <div style={{fontSize:42,marginBottom:8}}>🎹</div>
        <h1 style={{
          fontSize:"clamp(28px,6vw,48px)",
          fontWeight:700,
          color:"#fff",
          margin:"0 0 8px",
          fontStyle:"italic",
          textShadow:"0 2px 12px rgba(0,0,0,0.12)",
        }}>
          Irene's Piano Coach
        </h1>
        <p style={{color:"rgba(255,255,255,0.88)",fontSize:16,margin:0,fontStyle:"italic"}}>
          Upload any sheet music · get your perfect arrangement ✨
        </p>
      </div>

      {/* Step pills */}
      <div style={{
        display:"flex",
        justifyContent:"center",
        gap:0,
        padding:"0 24px",
        marginTop:-24,
        position:"relative",
        zIndex:10,
      }}>
        {STEPS.map((s,i) => (
          <div key={s} style={{display:"flex",alignItems:"center"}}>
            <div onClick={() => i < step && setStep(i)} style={{
              background: step===i ? "#4a90d9" : step>i ? "#7bc8a4" : "#fff",
              color: step>=i ? "#fff" : "#b0c4d8",
              border:`2px solid ${step===i ? "#4a90d9" : step>i ? "#7bc8a4" : "#dde8f0"}`,
              borderRadius:24,
              padding:"6px 16px",
              fontSize:13,
              fontWeight:600,
              cursor: i < step ? "pointer" : "default",
              whiteSpace:"nowrap",
              boxShadow: step===i ? "0 4px 16px rgba(74,144,217,0.3)" : "0 2px 8px rgba(0,0,0,0.08)",
              transition:"all 0.2s",
              fontFamily:"inherit",
            }}>
              {step>i ? "✓ " : `${i+1}. `}{s}
            </div>
            {i < STEPS.length-1 && (
              <div style={{width:20,height:2,background:step>i ? "#7bc8a4" : "#dde8f0",margin:"0 2px"}} />
            )}
          </div>
        ))}
      </div>

      <div style={{maxWidth:680,margin:"32px auto 0",padding:"0 20px"}}>

        {/* STEP 0 — Upload */}
        <div style={{
          background:"#fff",
          borderRadius:20,
          padding:"32px",
          boxShadow:"0 4px 24px rgba(74,144,217,0.10)",
          border:"1.5px solid #e0eef8",
          marginBottom:20,
        }}>
          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}>
            <div style={{
              width:36,height:36,borderRadius:"50%",
              background: step>=0 ? "linear-gradient(135deg,#4a90d9,#7bc8a4)" : "#eee",
              display:"flex",alignItems:"center",justifyContent:"center",
              color:"#fff",fontWeight:700,fontSize:16,flexShrink:0,
            }}>1</div>
            <div>
              <div style={{fontWeight:700,fontSize:18,color:"#1a2a3a"}}>Upload your sheet music</div>
              <div style={{fontSize:13,color:"#7a8fa6",fontStyle:"italic"}}>A photo from your phone works perfectly!</div>
            </div>
          </div>

          <div
            onClick={() => fileRef.current?.click()}
            onDrop={(e) => { e.preventDefault(); setDragOver(false); handleFile(e.dataTransfer.files[0]); }}
            onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
            onDragLeave={() => setDragOver(false)}
            style={{
              border:`2px dashed ${dragOver ? "#4a90d9" : image ? "#7bc8a4" : "#c8dff0"}`,
              borderRadius:14,
              padding:image ? 0 : "40px 24px",
              textAlign:"center",
              cursor:"pointer",
              background:dragOver ? "#f0f8ff" : image ? "transparent" : "#f8fcff",
              overflow:"hidden",
              transition:"all 0.2s",
            }}
          >
            <input ref={fileRef} type="file" accept="image/*" style={{display:"none"}}
              onChange={e => e.target.files && handleFile(e.target.files[0])} />
            {image ? (
              <div style={{position:"relative"}}>
                <img src={image} alt="Sheet music" style={{width:"100%",maxHeight:260,objectFit:"contain",display:"block",background:"#f8f8f8",borderRadius:10}} />
                <div style={{
                  position:"absolute",bottom:10,right:10,
                  background:"rgba(74,144,217,0.9)",
                  borderRadius:20,padding:"4px 12px",
                  fontSize:12,color:"#fff",fontWeight:600,
                }}>✏️ click to change</div>
              </div>
            ) : (
              <>
                <div style={{fontSize:52,marginBottom:12}}>🎼</div>
                <div style={{color:"#4a90d9",fontWeight:600,fontSize:15,marginBottom:4}}>
                  Drop your sheet music here
                </div>
                <div style={{color:"#9ab0c4",fontSize:13,fontStyle:"italic"}}>
                  or click to browse · JPG, PNG, WEBP
                </div>
              </>
            )}
          </div>

          {image && step === 1 && (
            <button onClick={() => setStep(1)} style={{
              marginTop:16,width:"100%",padding:"13px",borderRadius:10,border:"none",
              background:"linear-gradient(135deg,#4a90d9,#5ba8f0)",
              color:"#fff",fontSize:15,fontWeight:600,cursor:"pointer",fontFamily:"inherit",
              boxShadow:"0 4px 16px rgba(74,144,217,0.3)",
            }}>
              Looks good! Choose my key →
            </button>
          )}
        </div>

        {/* STEP 1 — Key */}
        {step >= 1 && (
          <div style={{
            background:"#fff",
            borderRadius:20,
            padding:"32px",
            boxShadow:"0 4px 24px rgba(123,200,164,0.12)",
            border:"1.5px solid #d8f0e4",
            marginBottom:20,
            opacity: step >= 1 ? 1 : 0.5,
          }}>
            <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}>
              <div style={{
                width:36,height:36,borderRadius:"50%",
                background: step>=1 ? "linear-gradient(135deg,#7bc8a4,#4a90d9)" : "#eee",
                display:"flex",alignItems:"center",justifyContent:"center",
                color:"#fff",fontWeight:700,fontSize:16,flexShrink:0,
              }}>2</div>
              <div>
                <div style={{fontWeight:700,fontSize:18,color:"#1a2a3a"}}>Choose your key</div>
                <div style={{fontSize:13,color:"#7a8fa6",fontStyle:"italic"}}>Pick a key that suits your voice or hands 🎵</div>
              </div>
            </div>

            <div style={{display:"flex",flexWrap:"wrap",gap:8}}>
              {KEYS.map(k => (
                <button key={k} onClick={() => setTargetKey(k)} style={{
                  padding: k==="Keep original" ? "8px 16px" : "8px 14px",
                  borderRadius:20,
                  border:`2px solid ${targetKey===k ? "#7bc8a4" : "#ddeef6"}`,
                  background:targetKey===k ? "linear-gradient(135deg,#7bc8a4,#a8dfc4)" : "#f8fcff",
                  color:targetKey===k ? "#fff" : "#4a7a8a",
                  fontSize:13,fontWeight:targetKey===k ? 700 : 400,
                  cursor:"pointer",fontFamily:"inherit",
                  boxShadow:targetKey===k ? "0 3px 12px rgba(123,200,164,0.35)" : "none",
                  transition:"all 0.15s",
                }}>{k === "Keep original" ? "🎵 Keep original" : k}</button>
              ))}
            </div>

            {targetKey && step === 1 && (
              <button onClick={() => setStep(2)} style={{
                marginTop:20,width:"100%",padding:"13px",borderRadius:10,border:"none",
                background:"linear-gradient(135deg,#7bc8a4,#5ab88a)",
                color:"#fff",fontSize:15,fontWeight:600,cursor:"pointer",fontFamily:"inherit",
                boxShadow:"0 4px 16px rgba(123,200,164,0.35)",
              }}>
                {targetKey === "Keep original" ? "Keep it as is →" : `Play in ${targetKey} →`}
              </button>
            )}
          </div>
        )}

        {/* STEP 2 — Difficulty */}
        {step >= 2 && (
          <div style={{
            background:"#fff",
            borderRadius:20,
            padding:"32px",
            boxShadow:"0 4px 24px rgba(255,220,80,0.12)",
            border:"1.5px solid #fef0c0",
            marginBottom:20,
          }}>
            <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}>
              <div style={{
                width:36,height:36,borderRadius:"50%",
                background:"linear-gradient(135deg,#f7c948,#f0a830)",
                display:"flex",alignItems:"center",justifyContent:"center",
                color:"#fff",fontWeight:700,fontSize:16,flexShrink:0,
              }}>3</div>
              <div>
                <div style={{fontWeight:700,fontSize:18,color:"#1a2a3a"}}>Choose your level</div>
                <div style={{fontSize:13,color:"#7a8fa6",fontStyle:"italic"}}>Be honest — we grow from where we are! 🌱</div>
              </div>
            </div>

            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
              {DIFFS.map(d => (
                <button key={d.id} onClick={() => setDifficulty(d.id)} style={{
                  padding:"16px 14px",borderRadius:14,textAlign:"left",cursor:"pointer",
                  border:`2px solid ${difficulty===d.id ? "#f7c948" : "#fef0c0"}`,
                  background:difficulty===d.id ? "linear-gradient(135deg,#fef9e7,#fef0c0)" : "#fffef8",
                  fontFamily:"inherit",
                  boxShadow:difficulty===d.id ? "0 4px 16px rgba(247,201,72,0.25)" : "none",
                  transition:"all 0.15s",
                }}>
                  <div style={{fontSize:24,marginBottom:6}}>{d.emoji}</div>
                  <div style={{fontSize:15,fontWeight:700,color:"#3a2a00",marginBottom:3}}>{d.label}</div>
                  <div style={{fontSize:12,color:"#9a7a30",fontStyle:"italic"}}>{d.desc}</div>
                </button>
              ))}
            </div>

            {difficulty && (
              <button onClick={handleConvert} disabled={loading} style={{
                marginTop:20,width:"100%",padding:"15px",borderRadius:10,border:"none",
                background:loading ? "#f0e8c0" : "linear-gradient(135deg,#f7c948,#f0a830)",
                color:loading ? "#c0a830" : "#3a2000",
                fontSize:15,fontWeight:700,cursor:loading ? "not-allowed" : "pointer",
                fontFamily:"inherit",fontStyle:"italic",
                boxShadow:loading ? "none" : "0 4px 16px rgba(247,201,72,0.4)",
                transition:"all 0.2s",
              }}>
                {loading ? "🎵 Arranging your music…" : `✨ Preview my arrangement →`}
              </button>
            )}

            {error && (
              <div style={{marginTop:14,background:"#fff0f4",border:"1.5px solid #f8c0cc",borderRadius:10,padding:"12px 16px",color:"#c04060",fontSize:13}}>
                ⚠️ {error}
              </div>
            )}
          </div>
        )}

        {/* STEP 3 — Result */}
        {step >= 3 && result && (
          <div style={{
            background:"#fff",
            borderRadius:20,
            padding:"32px",
            boxShadow:"0 4px 32px rgba(74,144,217,0.12)",
            border:"1.5px solid #e0eef8",
          }}>
            <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}>
              <div style={{
                width:36,height:36,borderRadius:"50%",
                background:"linear-gradient(135deg,#4a90d9,#f7c948)",
                display:"flex",alignItems:"center",justifyContent:"center",
                color:"#fff",fontWeight:700,fontSize:16,flexShrink:0,
              }}>🎹</div>
              <div>
                <div style={{fontWeight:700,fontSize:18,color:"#1a2a3a"}}>Your arrangement is ready!</div>
                <div style={{fontSize:13,color:"#7a8fa6",fontStyle:"italic"}}>
                  {targetKey === "Keep original" ? "Original key" : `Key of ${targetKey}`} · {selectedDiff?.label}
                </div>
              </div>
            </div>

            <div style={{
              background:"linear-gradient(135deg,#f8fcff,#f8fff8)",
              border:"1.5px solid #d8eef8",
              borderRadius:14,
              padding:"24px 28px",
              fontSize:14,
              lineHeight:1.9,
              whiteSpace:"pre-wrap",
              color:"#1a2a3a",
              marginBottom:20,
              maxHeight:480,
              overflowY:"auto",
            }}>
              {result}
            </div>

            <div style={{display:"flex",gap:10}}>
              <button onClick={handleDownloadPDF} style={{
                flex:1,padding:"13px",borderRadius:10,border:"none",
                background:"linear-gradient(135deg,#4a90d9,#5ba8f0)",
                color:"#fff",fontSize:14,fontWeight:600,cursor:"pointer",
                fontFamily:"inherit",
                boxShadow:"0 4px 16px rgba(74,144,217,0.3)",
              }}>
                📄 Download as PDF
              </button>
              <button onClick={() => { setStep(0); setImage(null); setImageBase64(null); setResult(null); setDifficulty(""); setTargetKey("Keep original"); }} style={{
                flex:1,padding:"13px",borderRadius:10,
                border:"2px solid #d8eef8",
                background:"#f8fcff",
                color:"#4a90d9",fontSize:14,fontWeight:600,cursor:"pointer",
                fontFamily:"inherit",
              }}>
                🎼 Start over
              </button>
            </div>
          </div>
        )}

        <div style={{textAlign:"center",marginTop:32,color:"#b0c8d8",fontSize:12,fontStyle:"italic"}}>
          made with 🎹 love · Irene's Piano Coach
        </div>
      </div>
    </main>
  );
}
